apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-http
  namespace: {{ .Values.namespace.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace.name }}-enforce-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: jenkins.houli.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8080
