---

- hosts: k3s_cluster
  become: true
  remote_user: hla
  roles:
    - common
    - set_static_ip
    - k3s_prereq
    - download_k3s
    - k3s_cgroup_support
  vars_files:
      - ../vars/main.yaml

- hosts: k3smaster
  become: true
  remote_user: hla
  roles:
    - role: k3s/master
  vars_files:
      - ../vars/main.yaml

- hosts: k3snodes
  become: true
  remote_user: hla
  roles:
    - role: k3s/node
  vars_files:
      - ../vars/main.yaml

