- name: Pre tasks
  hosts: certbot
  become: true
  roles:
    - common
  vars_files:
      - ../vars/main.yaml

- name: Certbot
  hosts: certbot
  become: true
  roles:
    - certbot
  vars_files:
    - ../vars/main.yaml
